#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

bindkey -e

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export CURL_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/curl"
# export VIM_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/vim"
export VIM_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
export VIMINIT='source $MYVIMRC'
# export MYVIMRC='~/.config/vim/vimrc'
export MYVIMRC='~/.config/nvim/init.vim'
export EDITOR="nvim"

# for scripts in mpv
mkdir -p /tmp/mpv/
launchctl setenv MPV_CHOPCHOP_OUTPUT_DIR "/tmp/mpv/"

# [ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &
